import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsOSynapticFx: SidebarsConfig = {
  osynapticFxSidebar: [
    'intro',
    {
      type: 'category',
      label: 'English Docs',
      items: [{type: 'autogenerated', dirName: 'en_GB'}],
    },
  ],
};

export default sidebarsOSynapticFx;

