import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsZh: SidebarsConfig = {
  tutorialSidebarZh: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsZh;
