import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '📚 Documentation Center',
      collapsible: true,
      collapsed: false,
      items: [
        'Home',
        'intro',
      ],
    },
    {
      type: 'category',
      label: '🚀 Quick Start',
      collapsible: true,
      collapsed: false,
      items: [
        'QUICK_START',
        'README',
      ],
    },
    {
      type: 'category',
      label: '📖 Tutorials',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-basics',
        },
        {
          type: 'autogenerated',
          dirName: 'tutorial-extras',
        },
      ],
    },
    {
      type: 'category',
      label: '🏗️ Architecture',
      collapsible: true,
      collapsed: false,
      items: [
        'ARCHITECTURE',
        'DOCUMENT_ORGANIZATION',
        'DOCUMENTATION_ORGANIZATION_FINAL',
        {
          type: 'autogenerated',
          dirName: 'architecture',
        },
      ],
    },
    {
      type: 'category',
      label: '⚙️ Core API',
      collapsible: true,
      collapsed: false,
      items: [
        'CORE_API',
        'RSCORE_API',
        'PYCORE_RUST_API',
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: '✨ Features',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'features',
        },
      ],
    },
    {
      type: 'category',
      label: '📋 Guides',
      collapsible: true,
      collapsed: false,
      items: [
        'QUICK_START',
        'CONFIG_SCHEMA',
        'ID_LEASE_CONFIG_REFERENCE',
        'ID_LEASE_SYSTEM',
        'TRANSPORTER_PLUGIN',
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    {
      type: 'category',
      label: '🔌 Plugins',
      collapsible: true,
      collapsed: false,
      items: [
        'TRANSPORTER_PLUGIN',
        {
          type: 'autogenerated',
          dirName: 'plugins',
        },
      ],
    },
    {
      type: 'category',
      label: '🌍 Internationalization',
      collapsible: true,
      collapsed: false,
      items: [
        'I18N',
        'MULTI_LANGUAGE_GUIDE',
        'LOCALIZATION_SUMMARY',
      ],
    },
    {
      type: 'category',
      label: '📊 Releases & Reports',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'releases',
        },
        {
          type: 'autogenerated',
          dirName: 'reports',
        },
        'COMPLETION_REPORT',
        'TRANSLATION_FINAL_REPORT',
      ],
    },
    {
      type: 'category',
      label: '🔧 Internal',
      collapsible: true,
      collapsed: false,
      items: [
        'Navigation',
        'ROOT_CLEANUP_COMPLETE',
        {
          type: 'autogenerated',
          dirName: 'internal',
        },
      ],
    },
  ],
};

export default sidebars;
