import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '📚 文档中心',
      collapsible: true,
      collapsed: false,
      items: [
        'Home',
        'intro',
      ],
    },
    {
      type: 'category',
      label: '🚀 快速开始',
      collapsible: true,
      collapsed: false,
      items: [
        'QUICK_START',
        'README',
      ],
    },
    {
      type: 'category',
      label: '📖 教程',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-basics',
        },
        {
          type: 'autogenerated',
          dirName: 'tutorial-extras',
        },
      ],
    },
    {
      type: 'category',
      label: '🏗️ 架构',
      collapsible: true,
      collapsed: false,
      items: [
        'ARCHITECTURE',
        'DOCUMENT_ORGANIZATION',
        'DOCUMENTATION_ORGANIZATION_FINAL',
        {
          type: 'autogenerated',
          dirName: 'architecture',
        },
      ],
    },
    {
      type: 'category',
      label: '⚙️ 核心 API',
      collapsible: true,
      collapsed: false,
      items: [
        'CORE_API',
        'RSCORE_API',
        'PYCORE_RUST_API',
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: '✨ 功能特性',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'features',
        },
      ],
    },
    {
      type: 'category',
      label: '📋 指南',
      collapsible: true,
      collapsed: false,
      items: [
        'QUICK_START',
        'CONFIG_SCHEMA',
        'ID_LEASE_CONFIG_REFERENCE',
        'ID_LEASE_SYSTEM',
        'TRANSPORTER_PLUGIN',
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    {
      type: 'category',
      label: '🔌 插件',
      collapsible: true,
      collapsed: false,
      items: [
        'TRANSPORTER_PLUGIN',
        {
          type: 'autogenerated',
          dirName: 'plugins',
        },
      ],
    },
    {
      type: 'category',
      label: '🌍 国际化',
      collapsible: true,
      collapsed: false,
      items: [
        'I18N',
        'MULTI_LANGUAGE_GUIDE',
        'INDEX',
      ],
    },
    {
      type: 'category',
      label: '📊 发布与报告',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'releases',
        },
        {
          type: 'autogenerated',
          dirName: 'reports',
        },
        'COMPLETION_REPORT',
      ],
    },
    {
      type: 'category',
      label: '🧩 产品',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'link',
          label: 'OSynaptic-FX 文档',
          href: '/docs/osynaptic-fx/intro',
        },
        {
          type: 'link',
          label: 'Nexa 文档',
          href: '/docs/nexa/intro',
        },
      ],
    },
    {
      type: 'category',
      label: '🔧 内部',
      collapsible: true,
      collapsed: false,
      items: [
        'Navigation',
        'ROOT_CLEANUP_COMPLETE',
        {
          type: 'autogenerated',
          dirName: 'internal',
        },
      ],
    },
  ],
};

export default sidebars;
