import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Documentation Center',
      collapsible: true,
      collapsed: false,
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'Quick Start',
      collapsible: true,
      collapsed: false,
      items: ['QUICK_START', 'README'],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsible: true,
      collapsed: false,
      items: [
        'ARCHITECTURE',
        {type: 'autogenerated', dirName: 'architecture'},
      ],
    },
    {
      type: 'category',
      label: 'API',
      collapsible: true,
      collapsed: false,
      items: [
        'CORE_API',
        'RSCORE_API',
        'PYCORE_RUST_API',
        {type: 'autogenerated', dirName: 'api'},
      ],
    },

    {
      type: 'category',
      label: 'Guides',
      collapsible: true,
      collapsed: false,
      items: [
        'QUICK_START',
        'CONFIG_SCHEMA',
        'ID_LEASE_CONFIG_REFERENCE',
        'ID_LEASE_SYSTEM',
        'TRANSPORTER_PLUGIN',
        {type: 'autogenerated', dirName: 'guides'},
      ],
    },
    {
      type: 'category',
      label: 'Plugins',
      collapsible: true,
      collapsed: false,
      items: ['TRANSPORTER_PLUGIN', {type: 'autogenerated', dirName: 'plugins'}],
    },
    {
      type: 'category',
      label: 'Internationalization',
      collapsible: true,
      collapsed: false,
      items: ['I18N', 'MULTI_LANGUAGE_GUIDE'],
    },
    {
      type: 'category',
      label: 'Releases',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'releases'}],
    },
    {
      type: 'category',
      label: 'Reports',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'reports'}],
    },
    {
      type: 'category',
      label: 'Products',
      collapsible: true,
      collapsed: false,
      items: [
        {type: 'link', label: 'OSynaptic-FX Docs', href: '/docs/osynaptic-fx/intro'},
        {type: 'link', label: 'Nexa Docs', href: '/docs/nexa/intro'},
      ],
    },
    {
      type: 'category',
      label: 'Internal',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'internal'}],
    },

  ],
};

export default sidebars;
