import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsOSynapticFx: SidebarsConfig = {
  osynapticFxSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsOSynapticFx;

