import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsPlaybooks: SidebarsConfig = {
  playbooksSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsPlaybooks;

