import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsExtensions: SidebarsConfig = {
  extensionsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsExtensions;

