import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsZh: SidebarsConfig = {
  tutorialSidebarZh: [
    {
      type: 'category',
      label: '开始阅读',
      collapsible: true,
      collapsed: false,
      items: [
        'intro',
        'Home',
        'Navigation',
        'INDEX',
        'README',
        'QUICK_START',
        'ARCHITECTURE',
        'API',
        'CORE_API',
        'CONFIG_SCHEMA',
        'ID_LEASE_SYSTEM',
        'ID_LEASE_CONFIG_REFERENCE',
        'PYCORE_RUST_API',
        'RSCORE_API',
        'TRANSPORTER_PLUGIN',
      ],
    },
    {
      type: 'category',
      label: '架构',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
    {
      type: 'category',
      label: 'API 与指南',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'api'},
        {type: 'autogenerated', dirName: 'guides'},
      ],
    },
    {
      type: 'category',
      label: '功能与插件',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'features'},
        {type: 'autogenerated', dirName: 'plugins'},
      ],
    },
    {
      type: 'category',
      label: '发布与报告',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'releases'},
        {type: 'autogenerated', dirName: 'reports'},
      ],
    },
    {
      type: 'category',
      label: '内部文档',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'internal'}],
    },
    {
      type: 'category',
      label: '其他根目录文档',
      collapsible: true,
      collapsed: true,
      items: [
        'COMPLETION_REPORT',
        'DOCUMENT_ORGANIZATION',
        'DOCUMENTATION_ORGANIZATION_FINAL',
        'ROOT_CLEANUP_COMPLETE',
        'MULTI_LANGUAGE_GUIDE',
        'I18N',
        'FINAL_LOCALIZATION_REPORT_2026',
        'LOCALIZATION_SUMMARY',
        'TIER3_TRANSLATION_PLAN',
        'TIER3_TRANSLATION_PROGRESS',
        'TRANSLATION_COMPLETION_SUMMARY',
        'TRANSLATION_CONTINUATION_PROGRESS',
        'TRANSLATION_FINAL_REPORT',
        'TRANSLATION_FINAL_SUMMARY',
        'TRANSLATION_PROGRESS_REPORT',
      ],
    },
  ],
};

export default sidebarsZh;
